/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited. This file is generated by Next.js.
// This file is for type checking and cannot be used for other purposes.
